# Generated by Django 3.0.5 on 2020-04-30 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pub',
            options={'permissions': (('can_publish', 'Can published'),)},
        ),
        migrations.AlterField(
            model_name='pub',
            name='is_pub',
            field=models.BooleanField(default=False, verbose_name='Was published'),
        ),
        migrations.AlterField(
            model_name='pub',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
