# Generated by Django 3.0.5 on 2020-04-30 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200430_0713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pub',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
